// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RpcChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package skynet.ant.rpc.core;

/**
 * 会话响应（回调）
 **/
public interface _RpcResponseOperations
{
    /**
     * 会话结果回调 
     * @param result 响应结果 
     * @param __current The Current object for the invocation.
     * @return 会话状态
     **/
    RpcStatus callback(RpcResult result, Ice.Current __current);
}
