// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RpcChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package skynet.ant.rpc.core;

/**
 * 会话请求 
 **/
public interface _RpcRequestOperationsNC
{
    /**
     * 会话开始
     * @param param 会话请求参数 
     * @return 会话状态
     **/
    RpcStatus begin(RpcParam param);

    /**
     * 会话进行中
     * @param sessionId 会话Id
     * @param content 会话内容
     * @return 会话状态
     **/
    RpcStatus post(String sessionId, byte[] content);

    /**
     * 会话结束
     * @param sessionId 会话Id
     * @return 会话状态
     **/
    RpcStatus end(String sessionId);

    /**
     * 通用远程方法
     * @param parameter 调用参数
     * @return 调用结果
     **/
    byte[] call(byte[] parameter);
}
