// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RpcChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package skynet.ant.rpc.core;

/**
 * 会话响应（回调）
 **/
public final class RpcResponsePrxHelper extends Ice.ObjectPrxHelperBase implements RpcResponsePrx
{
    private static final String __callback_name = "callback";

    /**
     * 会话结果回调 
     * @param result 响应结果 
     * @return 会话状态
     **/
    public RpcStatus callback(RpcResult result)
    {
        return callback(result, null, false);
    }

    /**
     * 会话结果回调 
     * @param result 响应结果 
     * @param __ctx The Context map to send with the invocation.
     * @return 会话状态
     **/
    public RpcStatus callback(RpcResult result, java.util.Map<String, String> __ctx)
    {
        return callback(result, __ctx, true);
    }

    private RpcStatus callback(RpcResult result, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "callback", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("callback");
                    __delBase = __getDelegate(false);
                    _RpcResponseDel __del = (_RpcResponseDel)__delBase;
                    return __del.callback(result, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     **/
    public Ice.AsyncResult begin_callback(RpcResult result)
    {
        return begin_callback(result, null, false, null);
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_callback(RpcResult result, java.util.Map<String, String> __ctx)
    {
        return begin_callback(result, __ctx, true, null);
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     **/
    public Ice.AsyncResult begin_callback(RpcResult result, Ice.Callback __cb)
    {
        return begin_callback(result, null, false, __cb);
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_callback(RpcResult result, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_callback(result, __ctx, true, __cb);
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     **/
    public Ice.AsyncResult begin_callback(RpcResult result, Callback_RpcResponse_callback __cb)
    {
        return begin_callback(result, null, false, __cb);
    }

    /**
     * 会话结果回调 
     * @param __cb The callback object for the operation.
     * @param result 响应结果 
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_callback(RpcResult result, java.util.Map<String, String> __ctx, Callback_RpcResponse_callback __cb)
    {
        return begin_callback(result, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_callback(RpcResult result, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__callback_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __callback_name, __cb);
        try
        {
            __result.__prepare(__callback_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            result.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    /**
     * ice_response indicates that
     * the operation completed successfully.
     * @param __ret (return value) 会话状态
     **/
    public RpcStatus end_callback(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __callback_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            RpcStatus __ret;
            __ret = new RpcStatus();
            __ret.__read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static RpcResponsePrx checkedCast(Ice.ObjectPrx __obj)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof RpcResponsePrx)
            {
                __d = (RpcResponsePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static RpcResponsePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof RpcResponsePrx)
            {
                __d = (RpcResponsePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static RpcResponsePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static RpcResponsePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static RpcResponsePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof RpcResponsePrx)
            {
                __d = (RpcResponsePrx)__obj;
            }
            else
            {
                RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static RpcResponsePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        RpcResponsePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            RpcResponsePrxHelper __h = new RpcResponsePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::skynet::ant::rpc::core::RpcResponse"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _RpcResponseDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _RpcResponseDelD();
    }

    public static void __write(IceInternal.BasicStream __os, RpcResponsePrx v)
    {
        __os.writeProxy(v);
    }

    public static RpcResponsePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            RpcResponsePrxHelper result = new RpcResponsePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
