// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RpcChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package skynet.ant.rpc.core;

/**
 * RPC 结果
 **/
public class RpcResult implements Cloneable, java.io.Serializable
{
    /**
     * 跟踪id（可以是业务Id）
     **/
    public String trackId;

    /**
     * 参数
     **/
    public String sessionId;

    /**
     * 会话结果
     **/
    public byte[] result;

    /**
     * 结果响应上下文
     **/
    public byte[] context;

    public RpcResult()
    {
    }

    public RpcResult(String trackId, String sessionId, byte[] result, byte[] context)
    {
        this.trackId = trackId;
        this.sessionId = sessionId;
        this.result = result;
        this.context = context;
    }

    public boolean
    equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RpcResult _r = null;
        if(rhs instanceof RpcResult)
        {
            _r = (RpcResult)rhs;
        }

        if(_r != null)
        {
            if(trackId != _r.trackId)
            {
                if(trackId == null || _r.trackId == null || !trackId.equals(_r.trackId))
                {
                    return false;
                }
            }
            if(sessionId != _r.sessionId)
            {
                if(sessionId == null || _r.sessionId == null || !sessionId.equals(_r.sessionId))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(result, _r.result))
            {
                return false;
            }
            if(!java.util.Arrays.equals(context, _r.context))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::skynet::ant::rpc::core::RpcResult");
        __h = IceInternal.HashUtil.hashAdd(__h, trackId);
        __h = IceInternal.HashUtil.hashAdd(__h, sessionId);
        __h = IceInternal.HashUtil.hashAdd(__h, result);
        __h = IceInternal.HashUtil.hashAdd(__h, context);
        return __h;
    }

    public Object
    clone()
    {
        Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(trackId);
        __os.writeString(sessionId);
        byteArrayHelper.write(__os, result);
        byteArrayHelper.write(__os, context);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        trackId = __is.readString();
        sessionId = __is.readString();
        result = byteArrayHelper.read(__is);
        context = byteArrayHelper.read(__is);
    }

    public static final long serialVersionUID = 8597650798317473435L;
}
