// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RpcChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package skynet.ant.rpc.core;

/**
 * 会话响应（回调）
 **/
public interface RpcResponse extends Ice.Object,
                                     _RpcResponseOperations, _RpcResponseOperationsNC
{
    public static final long serialVersionUID = 374077268974800864L;
}
